#????
spring:
  profiles:
    active: prod
#    include: prodDataSource  springboot 2.4.0 ?????include,??group
    group:
      dev:
        devDataSource
      prod:
        prodDataSource
server:
  servlet:
    context-path: /demo